version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_GRAPHCMS_ENDPOINT=${NEXT_PUBLIC_GRAPHCMS_ENDPOINT}
      - GRAPHCMS_TOKEN=${GRAPHCMS_TOKEN}
    env_file:
      - .env